name: Run Cypress Tests

on: [push] # Runs on every push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests (Only One File)
        uses: cypress-io/github-action@v6
        with:
          spec: cypress\e2e\locaters.cy.js  # Change to your test file
