name: Fill Hkms

on:
  schedule:
    - cron: '30 5 * * 1-6' # Runs at 11:00 AM IST (5:30 AM UTC), Monday to Saturday
  workflow_dispatch: # Allows manual triggering

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Adjust as needed

      - name: Install Dependencies
        run: npm install # or yarn install if your project requires it

      - name: Verify Cypress Installation
        run: npx cypress install

      - name: Run Cypress Tests
        id: cypress
        continue-on-error: true  # Allows next steps to execute even if tests fail
        uses: cypress-io/github-action@v6
        with:
          spec: "cypress/e2e/hkms.cy.js"

      - name: Check for Screenshots
        id: check_screenshots
        run: |
          if [ -d "cypress/screenshots" ] && [ "$(ls -A cypress/screenshots)" ]; then
            echo "Screenshots found."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "No screenshots found."
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Upload Cypress Screenshots (if tests fail and screenshots exist)
        if: failure() && env.exists == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*
