name: Suterday funsheet Test 

on:  
  schedule:
  - cron: '30 3 * * 1'  # Runs at 9:30 AM IST (3:30 AM UTC) every Monday
  - cron: '30 5 * * 6'  # Runs at 11:30 AM IST (5:30 AM UTC) every Saturday
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          spec: "cypress/e2e/fundsheetcypress.cy.js"

      - name: Upload Cypress Screenshots (on failure)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
               
      - name: Upload Cypress Screenshots (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4  # Update to v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*

