name: Run Cypress Tests on Dev Push

on:
  repository_dispatch:
    types: [run-cypress]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Cypress Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run
