name: Suterday funsheet Test 

on:  
  schedule:
  - cron: '0 22 * * 6'  # Runs at 22:00 (10 PM) every Saturday

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-cache-

      - name: Install dependencies
        run: npm ci  # Faster & reliable than 'npm install'

      # Run a specific Cypress test file
      - name: Run Cypress Test for Specific File
        run: Run Cypress Tests --spec "cypress/integration/specific-test.spec.js"

      - name: Upload Cypress Screenshots (on failure)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
